### ISSUE TITLE
Affine self hosted - issue creating docker container - Cannot find module '/app/scripts/self-host-predeploy.js'

### ISSUE THREAD

**Issue by ilpratti** [toeverything/AFFiNE#14390]
Dear,
I followed the guide @ https://docs.affine.pro/self-host-affine/install/docker-compose-recommend
to install affine self hosted.
I'm using debian 12 and Docker Compose version v5.0.2.
STEP I followed:
1. I created a folder "affine"
2. I created .yml file (copy and past from the template in the guide)
3. I created .env file (copy and past from the templete in the guide, just added the database password)
4. I started the container 
5.  I got error in the creation of container affine_migration_job, see below

Could you help me to figure out what I'm doing wrong?

```
root@server:/home/docker/affine$ls
totale 16K
drwxr-xr-x  2 alfonso alfonso 4,0K  7 feb 07.43 .
drwxr-xr-x 24 root    root    4,0K  7 feb 07.41 ..
-rw-r--r--  1 alfonso alfonso 2,3K  7 feb 07.42 affine.yml
-rw-r--r--  1 alfonso alfonso  747  7 feb 07.43 .env

oot@server:/home/docker/affine$docker compose -f affine.yml up -d
[+] up 5/5
 ✔ Network affine_default         Created                                                                                                                       0.1ss
 ✔ Container affine_redis         Healthy                                                                                                                       11.5s
 ✔ Container affine_postgres      Healthy                                                                                                                       11.5s
 ✘ Container affine_migration_job Error service "affine_migration" didn't complete successfully: exit 1                                                         11.5s
 ✔ Container affine_server        Created                                                                                                                       0.0ss
service "affine_migration" didn't complete successfully: exit 1


root@server:/home/docker/affine$docker logs affine_migration_job
node:internal/modules/cjs/loader:1386
  throw err;
  ^

Error: Cannot find module '/app/scripts/self-host-predeploy.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.22.0


root@server:/home/docker/affine$docker ps -a | grep affine
966ccdd1c5b5   ghcr.io/toeverything/affine:stable                               "docker-entrypoint.s…"   About a minute ago   Created                                                                                                                                                                 affine_server

ec83cdb8bab2   ghcr.io/toeverything/affine:stable                               "docker-entrypoint.s…"   About a minute ago   Exited (1) About a minute ago                                                                                                                                           affine_migration_job

f4e6a1be4781   redis                                                            "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)     6379/tcp                                                                                                                                affine_redis

01d2773eccc2   pgvector/pgvector:pg16                                           "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)     5432/tcp                                                                                                                                affine_postgres

```

```
root@server:/home/docker/affine$cat affine.yml 
name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_server
    ports:
      - '${PORT:-3010}:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
      - AFFINE_INDEXER_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
```

```
root@server:/home/docker/affine$cat .env
# select a revision to deploy, available values: stable, beta, canary
AFFINE_REVISION=stable

# set the port for the server container it will expose the server on
PORT=3010

# set the host for the server for outgoing links
# AFFINE_SERVER_HTTPS=true
# AFFINE_SERVER_HOST=affine.yourdomain.com
# or 
# AFFINE_SERVER_EXTERNAL_URL=https://affine.yourdomain.com

# position of the database data to persist
DB_DATA_LOCATION=~/.affine/self-host/postgres/pgdata
# position of the upload data(images, files, etc.) to persist
UPLOAD_LOCATION=~/.affine/self-host/storage
# position of the configuration files to persist
CONFIG_LOCATION=~/.affine/self-host/config

# database credentials
DB_USERNAME=affine
DB_PASSWORD=passwordinvented1234
DB_DATABASE=affine
```

**Comment by JavaJix** [comment]
same issue here after updating to 0.26.0

`affine_migration_job  | node:internal/modules/cjs/loader:1386
affine_migration_job  |   throw err;
affine_migration_job  |   ^
affine_migration_job  | 
affine_migration_job  | Error: Cannot find module '/app/scripts/self-host-predeploy.js'
affine_migration_job  |     at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
affine_migration_job  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
affine_migration_job  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
affine_migration_job  |     at Function._load (node:internal/modules/cjs/loader:1192:37)
affine_migration_job  |     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
affine_migration_job  |     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
affine_migration_job  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
affine_migration_job  |     at node:internal/main/run_main_module:36:49 {
affine_migration_job  |   code: 'MODULE_NOT_FOUND',
affine_migration_job  |   requireStack: []
affine_migration_job  | }
affine_migration_job  | 
affine_migration_job  | Node.js v22.22.0
affine_migration_job exited with code 1`

**Comment by darkskygit** [comment]
0.26.1 container image has fixed the issue, please upgrade the container
